name: On Pull Request check

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - '.github/workflows/on-pullrequest.yml'

jobs:
  small-test:
    uses: ./.github/workflows/job-test-small.yml
    with:
      with-coverage: true
